### ISSUE TITLE
It seemed that the patient weren't deleted even when the dataset was deleted

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-client#108]
### Problem description

```
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Content-Length': '730'})
HTTP response body: {
  "detail": "Index build failed: 5f837278-c225-4c48-988b-b14b2546ae54: Collection nlpsandbox.patient ( 3e21599d-b3e6-4a49-94a6-d6db54de3688 ) :: caused by :: E11000 duplicate key error collection: nlpsandbox.patient index: resourceName_1 dup key: { resourceName: null }, full error: {'ok': 0.0, 'errmsg': 'Index build failed: 5f837278-c225-4c48-988b-b14b2546ae54: Collection nlpsandbox.patient ( 3e21599d-b3e6-4a49-94a6-d6db54de3688 ) :: caused by :: E11000 duplicate key error collection: nlpsandbox.patient index: resourceName_1 dup key: { resourceName: null }', 'code': 11000, 'codeName': 'DuplicateKey', 'keyPattern': {'resourceName': 1}, 'keyValue': {'resourceName': None}}",
  "status": 500,
  "title": "Internal error"
}
```

#### Steps to reproduce the issue

I haven't tested this yet, but
1. Create a dataset
2. Create multiple patients
3. Delete the dataset
4. Try to store a patient with the same id
5. Maybe it will fail?  Or the above was just a fluke.

I looked at the server code and there is definitely code to delete the patients when the dataset is deleted.

**Comment by tschaffter** [comment]
I cannot reproduce this error. What I did:

1. Start from an empty DB
2. Create a dataset, create a FHIR store, create a patient
3. Delete the dataset
4. Use Robo 3T to confirm that the DB is empty

We are no longer using patient ID like the one in the log ("3e21599d-b3e6-4a49-94a6-d6db54de3688"). This ID seems to indicate that it was generated by the DB, which is no longer the case since last week.

I'll release the version 1.0.0 of the data node this afternoon. Please give it a try with this release and make sure to have removed the Docker volume before deploying the data node.

**Comment by thomasyu888** [comment]
Ya this issue was fixed when I removed the docker volume.  I'll close this issue.
