### ISSUE TITLE
Review example-patient-bundles.json

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-client#113]
### Is your proposal related to a problem?

How will data hosting sites load their data into their own data nodes?

### Describe the solution you'd like

We could potentially provide some code that takes in as input `example-patient-bundles.json` and pushes the evaluation dataset.  This is motivated from when I started creating a cli function for storing notes only to realize that you must have a patient stored first prior to creating the note.  

### Describe alternatives you've considered

Describe the following workflow (Essentially the example.py file, but we use `example-patient-bundles.json` which may or may not be the format at which other sites)

1. Create dataset
2. Create Fhir Store
3. Create Annotation Store
4. Push Patients
5. Push Notes
6. Push Annotations (Gold standard)

**Comment by tschaffter** [comment]
> We could potentially provide some code that takes in as input example-patient-bundles.json and pushes the evaluation dataset. 

We example script [push_dataset.py](https://github.com/nlpsandbox/nlpsandbox-client/blob/develop/examples/push_dataset.py) already does that. Do you have in mind to provide a more formal and documented way of pushing a dataset to their Data Node instance?

An intermediate step would be to update the above script so that it uses SDK functions of the Python client.

Initially most organizations should have their data in a DB, stored using one of the standard available. In order to store the data in the data node instance, they will probably have a Python script or similar that 1) grab the data from their organization DB, 2) format the data according to the NLP Sandbox schemas, 3) push the data to the data node.

Providing a Python example script that relies on a data stored in a JSON file is probably the best way to provide a simple example that organizations can edit to read data from a different source.

Tagging @gkowalski who has experience pulling / processing / pushing clinical notes.

**Comment by thomasyu888** [comment]
> We example script push_dataset.py already does that. Do you have in mind to provide a more formal and documented way of pushing a dataset to their Data Node instance?

The `push_dataset.py` uses `example-patient-bundles.json`, but as you said, not necessarily all sites will format their input bundle in this way.  My thoughts are:

1.  Provide a standard `bundle.json` format so sites could write code to create this bundle and use our code to push into their own data node.  We can then provide a function like: `nlp-cli data-node push-dataset --bundle bundle.json`
2. Provide step by step instructions (basically write out `push_dataset.py` - for sites that don't have this `bundle.json`)
    a. Create dataset
    b. Create Fhirstore
    c. Create AnnotationStore
    d. Create a patient
    e. Create notes per patient (depends on d)
    f.  Create goldstandard (annotation) per note (depends on e)

> Providing a Python example script that relies on a data stored in a JSON file is probably the best way to provide a simple example that organizations can edit to read data from a different source.

It seems from this text that you are leaning towards Point 2 that I stated above.  I suppose sites can also just infer all these from `push_dataset.py`.  Maybe we don't actually have to do any more work.

**Comment by tschaffter** [comment]
@gkowalski Tom told me that you asked him how to push data to an instance of the Data Node. The *examples* folder of this repository includes an example that reads clinical note and patient data from a JSON file, then create a Dataset in the data node and store the clinical notes and patient information there.

If you dataset is large, it would not make sense to create such a JSON file. However, you should be able to re-use most of the example script to store data in your instance of the data node. You would just get the original data in a different way, for example by querying one of MCW database.

Please let me know if you have suggestion one how to improve this example script in a way that can help other pushing data into their own instance of the data node.

**Comment by tschaffter** [comment]
@tschaffter Reformat JSON bundle (add `Note.noteId`), then Tom will update this script and we will close this ticket.

**Comment by tschaffter** [comment]
@thomasyu888 Let's review this ticket on Monday. I did some nice work on the generation of the JSON bundle but I haven't change the structure of the data. The dataset below has been created for the schemas 1.1.2, which has not been released yet.

https://www.synapse.org/#!Synapse:syn25815737

**Comment by tschaffter** [comment]
@thomasyu888 This issue should now be fixed. [This notebook](https://github.com/nlpsandbox/i2b2-phi-dataset) should enable anyone to generate the 2014 i2b2 dataset to the NLP Sandbox schemas.
