### ISSUE TITLE
Get rid of get_or_create_resource in example script

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-client#135]
### Is your proposal related to a problem?

The use of a function that gets a resource OR creates it and gets it is a bad practice. If the user is requesting a resource and it does not exists, a 404 error should be returned to the user instead of assuming that he/she wants the resource to be created.

### Describe the solution you'd like

Get rid of the function `get_or_create_resource ` in the example script.

**Comment by thomasyu888** [comment]
I personally think it would be bad practice if the function was labelled as `create` or `get`, but it's pretty clear here that the function will create a resource if it doesn't exist, and get it if it does.

That being said, this was done because you may not want to have to add in the try catch yourself if the creation of the 300th patient failed and you have to rerun your creation script.  It's no different then having all the try catches that you had in the first place, it just makes the code more condensed.

**Comment by tschaffter** [comment]
I looked at the script I wrote originally and you're right, what you are doing is just making the script more condensed. Generally speaking, running the script twice in a row should lead to the same dataset state in the data node. One way to achieve this is to start the script with DELETING the dataset (we know its resource name), then create the dataset, create the fhir store, etc. with no need to check that these resources already exist because we make sure to remove the dataset first thing in the script. With this new approach, running the script twice (if it completes successfully) grantees that the state of the dataset in the data node is the same.
