### ISSUE TITLE
Loading data into data node fails with example script

### ISSUE THREAD

**Issue by gkowalski** [nlpsandbox/nlpsandbox-client#149]
### Problem description

I ran the examples/push_dataset.py program to load the example data set into our data node and it failed to load the data.

#### Steps to reproduce the issue

I first edited the push_dataset.py and changed the host  line to read : 

host = "http://ourhost.mcw.edu:8080/api/v1"

Then ran the program : 

```
python push_dataset.py
Deleting exist dataset: test-dataset
Creating dataset: test-dataset
Creating Fhir Store: evaluation
Creating Annotation Store: goldstandard
Creating patient: 110
Creating note (110-01) for patient (110)
Traceback (most recent call last):
  File "push_dataset.py", line 114, in <module>
    note_create_request=note
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 764, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api/note_api.py", line 122, in __create_note
    return self.call_with_http_info(**kwargs)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 811, in call_with_http_info
    self.__validate_inputs(kwargs)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/api_client.py", line 711, in __validate_inputs
    configuration=self.api_client.configuration
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/model_utils.py", line 1403, in validate_and_convert_types
    check_type=_check_type
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/model_utils.py", line 1284, in attempt_convert_item
    configuration, spec_property_naming)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/model_utils.py", line 1202, in deserialize_model
    return model_class(**kw_args)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/model_utils.py", line 1564, in wrapped_init
    return fn(self, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'note_type'
```

#### Expected behavior

- Data loaded into data node 

#### Extra information

I edited the example-patient-bundles.json and put in values for "type" field  : 

       "type": "pathology",

and received the same error.

**Comment by thomasyu888** [comment]
@gkowalski , this also seems like an issue with the data node not being up to date.

**Comment by gkowalski** [comment]
I have done a git pull and have the latest code : 

cd data-node

$git remote -v
origin	https://github.com/nlpsandbox/data-node.git (fetch)
origin	https://github.com/nlpsandbox/data-node.git (push)

$git branch
* develop

$git log -1 --oneline
c6ef9d4 Revert python slim buster (#159)

Seems to be the latest from https://github.com/nlpsandbox/data-node

**Comment by gkowalski** [comment]
As for the nlpsandbox-client : 

cd ~/nlpsandbox-client

git remote -v 

$ git remote -v
origin	https://github.com/nlpsandbox/nlpsandbox-client.git (fetch)
origin	https://github.com/nlpsandbox/nlpsandbox-client.git (push)

$git branch
* develop

$ git log -1 --oneline
cf52697 Update README.md (#147)

which matches https://github.com/nlpsandbox/nlpsandbox-client

**Comment by tschaffter** [comment]
@gkowalski 

>   File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/datanode/model_utils.py", line 1564, in wrapped_init
    return fn(self, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'note_type'

This message tells us that the issue is related to a Python property named `note_type` in the file `datanode/model_utils.py`. The first thing to check is: Is this property part of the [Note schema](https://github.com/nlpsandbox/nlpsandbox-schemas/blob/cfcf11e144e1da93f816f1c9a183fe47e17927f2/openapi/commons/components/schemas/Note.yaml#L17), which is source of truth. The property `noteType` in the schemas - which is converted to lower kebab case in Python object (i.e. `note_type`) - does not exist (any more). So there is somewhere a reference to `noteType` (or `note_type` in Python) that should be renamed to `type`.

Here is a link to the file [datanode/model_utils.py](https://github.com/nlpsandbox/nlpsandbox-client/blob/develop/datanode/model_utils.py) listed in the error message. This file is part of the nlpsandbox-client and seems to have been generated automatically. This file does not include a reference to `note_type`. However, the client has two files that incorrectly include `note_type`: https://github.com/nlpsandbox/nlpsandbox-client/search?q=note_type. Several occurences are commented but one that is used in the integration test. The Note model included in the client is up to date and [reference `type`](https://github.com/nlpsandbox/nlpsandbox-client/blob/develop/datanode/model/note.py) and not `note_type`. So aside the type in the tests, the client seems up to date with the latest schemas.

@gkowalski Can you tell me what version of the NLP Sandbox client for Python you are using?

@thomasyu888 There's one thing that is weird: the [latest stable release that you created on GitHub is 1.0.0](https://github.com/nlpsandbox/nlpsandbox-client/releases) on March 22. However, the current version in https://github.com/nlpsandbox/nlpsandbox-client/blob/develop/nlpsandboxclient/__init__.py is 0.4.1. There is a mismatch there. There is indeed [a version 0.4.1 of the package on PyPi](https://pypi.org/manage/project/nlpsandbox-client/releases/), but it has been pushed on Feb 27, 2021. Looking at the log of the CI workflow that run when you created the release 1.0.0, I see that the CI workflow failed because PyPi detected that the version 0.4.1 already existed.

https://github.com/nlpsandbox/nlpsandbox-client/runs/2172520539

```
Run pypa/gh-action-pypi-publish@master
/usr/bin/docker run --name e4b38ca0d820604564a3174612a22558b3_bbbe30 --label 5588e4 --workdir /github/workspace --rm -e docker_repository -e pythonLocation -e INPUT_PASSWORD -e INPUT_USER -e INPUT_REPOSITORY_URL -e INPUT_PACKAGES_DIR -e INPUT_VERIFY_METADATA -e INPUT_SKIP_EXISTING -e INPUT_VERBOSE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/nlpsandbox-client/nlpsandbox-client":"/github/workspace" 5588e4:b38ca0d820604564a3174612a22558b3  "__token__" "***" "" "dist" "true" "false" "false"
Checking dist/nlpsandbox-client-0.4.1.tar.gz: PASSED
Uploading distributions to https://upload.pypi.org/legacy/
Uploading nlpsandbox-client-0.4.1.tar.gz

  0%|          | 0.00/122k [00:00<?, ?B/s]
  7%|▋         | 8.00k/122k [00:00<00:04, 28.2kB/s]
100%|██████████| 122k/122k [00:00<00:00, 180kB/s]  
NOTE: Try --verbose to see response content.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
File already exists. See https://pypi.org/help/#file-name-reuse for more information.
```

### Proposed solution

1. Open a PR to update the version of this package to 1.0.1 (`__init.py__`)
2. Create a new release version 1.0.1
3. Ask George to use the client version 1.0.1

**Comment by tschaffter** [comment]
Following the above discussion, we have just released the [NLP Sandbox client version 1.0.1](https://pypi.org/project/nlpsandbox-client/) for Python on PyPi.

@gkowalski Can you state whether you are using the client installed from PyPi or from source? If it's from source, us releasing the new version of the client won't help because the new release does not solve any know issues.

Please use the example script [push_dataset.py](https://github.com/nlpsandbox/nlpsandbox-client/blob/develop/examples/push_dataset.py) provided in this repository along with the sample of the i2b2 data ([example-patient-bundles.json](https://github.com/nlpsandbox/nlpsandbox-client/tree/develop/examples)).

**Comment by gkowalski** [comment]
I always use the source code . I didn't know of the pypi version  .

**Comment by tschaffter** [comment]
Please update your client (both the source and the pypi package have been updated). The client no longer has reference to `note_type` so you should not long get the error that you share above.

**Comment by gkowalski** [comment]
Works now . 

+ (venv) [crdw@darvin:~/nlpsandbox-client/examples]$ python push_dataset.py
+ Creating dataset: test-dataset
+ Creating Fhir Store: evaluation
+ Creating Annotation Store: goldstandard
+ Creating patient: 110
+ Creating note (110-01) for patient (110)
+ Creating annotation for note: 110-01
+ Creating note (110-02) for patient (110)
+ Creating annotation for note: 110-02
+ Creating note (110-03) for patient (110)
+ Creating annotation for note: 110-03
+ Creating note (110-04) for patient (110)
+ Creating annotation for note: 110-04
+ (venv) [crdw@darvin:~/nlpsandbox-client/examples]$
